// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/gossiper.proto

package cs739.gossiper;

public interface EchoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EchoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
